### ISSUE TITLE
[ Fix ]: Docs suggest "failureRedirect" as optional but throws Error when removed.

### ISSUE THREAD

**Issue by justin-hackin** [dev-xo/remix-auth-totp#66] opened 2024-05-29 15:44 UTC
In the example [here](https://github.com/dev-xo/totp-starter-example/blob/4f14dbc1696a81827f2708a88e1e16beec176edc/app/routes/login.tsx#L35) it is stated:

>  // The `failureRedirect` route will be used to render any possible error.
>  // If not provided, ErrorBoundary will be rendered instead.

When it is removed from the options, we get `Error: Missing required failureRedirect URL.` in a case that would normally succeed. I assumed what this comment meant is that failures will just throw instead of redirecting. Was that the intent?

**Comment by dev-xo** [comment] 2024-05-29 20:11
Good catch @justin-hackin, if you want to contribute to fixing that comment, it will be more than welcome. Otherwise, I will look into it whenever I get a moment.

Thank you for the catch

**Comment by justin-hackin** [comment] 2024-05-29 20:40
> Good catch @justin-hackin, if you want to contribute to fixing that comment, it will be more than welcome. Otherwise, I will look into it whenever I get a moment.
> 
> Thank you for the catch!

Hi, thanks for the invite. I'm pretty confused about how this library works (e.g. why is authenticate called on both login and verify in the example and what's going on under the hood). I don't think I'll be able to contribute.

**Comment by chiptus** [comment] 2024-06-07 05:39
@dev-xo do you expect the docs to be fixed? or the actual code?

**Comment by dev-xo** [comment] 2024-06-07 05:57
I think the issue is about the docs not matching the actual code behavior, at least it's what I'm able to understand. The fix is simple (docs related), sadly I'm kinda busy but I could look into it anytime soon.

Not sure if that's your question @chiptus, would appreciate some specification on it.

**Comment by chiptus** [comment] 2024-06-07 06:08
as you said docs are not matching the code. should the docs be fixed? or the code to match the docs?

**Comment by dev-xo** [comment] 2024-06-07 06:21
Code should be working as expected, so in this case, probably the docs should be fixed. Not sure if you want to contribute with a little PR, but if that's the case, it will be welcomed! ;)

**Comment by dev-xo** [comment] 2024-06-11 05:39
- https://github.com/dev-xo/remix-auth-totp/commit/771d7ef961751f6dffa07fd146c60640a553b7b5
- https://github.com/dev-xo/totp-starter-example/commit/b23f1639c8e992ea5be64da92d4b40028824ce24
- https://github.com/dev-xo/totp-flat-routes-example/commit/b2d406c28c59b0a3f913a5c2c3a65c3ef1c591f8
- https://github.com/dev-xo/totp-conform-example/commit/09b11f1637f727d0248bc1e6c00f48fb25141c42

Thanks for noticing this, @justin-hackin. If there's anything else, let me know 👍🏻

**Comment by dev-xo** [comment] 2024-06-11 05:40
- https://github.com/dev-xo/remix-auth-totp/commit/771d7ef961751f6dffa07fd146c60640a553b7b5
- https://github.com/dev-xo/totp-starter-example/commit/b23f1639c8e992ea5be64da92d4b40028824ce24
- https://github.com/dev-xo/totp-flat-routes-example/commit/b2d406c28c59b0a3f913a5c2c3a65c3ef1c591f8
- https://github.com/dev-xo/totp-conform-example/commit/09b11f1637f727d0248bc1e6c00f48fb25141c42

Thanks for noticing this, @justin-hackin. If there's anything else, let me know 👍🏻

**Closed by dev-xo** 2024-06-11 05:40 UTC
Labels: documentation
