### ISSUE TITLE
[ Feat ] Add support for different OTP sending methods.

### ISSUE THREAD

**Issue by chiptus** [dev-xo/remix-auth-totp#47] opened 2024-02-05 13:30 UTC
hey @dev-xo !

Thanks for the amazing work!

my app requires to support both email and whatsapp for sending the otp. I see that to send the otp I can customize `sendTOTP`.

Is there a way to pass the function different parameters so I know which method to send the otp?

Thanks,
Chaim

**Comment by dev-xo** [comment] 2024-02-05 18:27
Hello, @chiptus. Thanks for reaching out.

I don't think there is support for anything else than email for now, but we could look into this in the future. Currently, `remix-auth-totp@v3.0` will be released in the next week/s with some major changes, so I think we should wait for that first.

Feel free to open a pull request with a possible implementation; we'll be more than okay to review it and further discuss about it.

I will leave the issue open, as we could look into it soon.

**Comment by chiptus** [comment] 2024-02-06 08:08
as a workaround I send in my form the method, and send it accordingly. it requires me to add a validation function that does nothing (as I can't get the form values there), and validate in the send function.

would be cool to send a `context` object, and have a `contextGetter` function that I can use to customize it (the default will parse the email from the form, validate it and return the email as a property, while mine will check the method, validate accordingly and return `{method, email, phone}`

**Comment by dev-xo** [comment] 2024-02-07 02:17
Thoughts on this, @mw10013?

Any idea if we could extend the way people send the OTP, or is it already possible to handle it somehow?

**Comment by haus23** [comment] 2024-02-08 15:00
Hey @chiptus, your workaround is probably the only doable one.

Best implementation would be to have an input radio (name=method or what you like) on the login form, which switches the email-input and a second phone-input (with name email but type tel) - probably what you did already.

Then add a custom email-Validation, that allows phone numbers - or just do nothing as you suggested.

And in the sendTOTP-method look into the form for the requested sending  method.

@dev-xo @mw10013 This works only on the v2 branch, cause you are omitting request and especially form data in the v3-Version of sendTOTP

A major change would be to generalize the validation and send methods with the whole formData object, not just the email. Or some approach like chiptus mentioned or perhaps a generic strategy class.

**Comment by dev-xo** [comment] 2024-02-09 14:57
We'll probably discuss this before releasing the `v3`, in order to maintain this workaround until an official implementation or discussion starts.

Hope @mw10013 jumps on this talk to give his thoughts, as he's the one who has been working on the `v2` and `v3`, and at this point, he understands the overall strategy/module better than I do.

**Comment by mw10013** [comment] 2024-02-12 20:49
@chiptus: Thanks for presenting this compelling use case. `v3` is being finalized with request and form data removed from `sendTOTP`. Your use case gets them back into `v3`.

Will that suffice to cover your use case?

Can you provide more color on how a `context` object along with a `contextGetter` function would work within the flow of `remix-auth-totp`? Any pseudo code would help us understand more concretely.

**Comment by haus23** [comment] 2024-02-12 21:53
Hi all, bringing back request and form data back into sendTOTP is probably a good idea. Can't be wrong to give the "outer" side most of our known data. Alone the request is not sufficient, the client needs to clone it before. So form  data is ok!

Full acc with you all!

**Comment by chiptus** [comment] 2024-02-13 12:55
> @chiptus: Thanks for presenting this compelling use case. `v3` is being finalized with request and form data removed from `sendTOTP`. Your use case gets them back into `v3`.

great

> Will that suffice to cover your use case?

for now, for sure.

> Can you provide more color on how a `context` object along with a `contextGetter` function would work within the flow of `remix-auth-totp`? Any pseudo code would help us understand more concretely.

I imagine it like that:

```
authenticator.use(
  new TOTPStrategy(
    {
      secret: TOTP_ENCRYPTION_SECRET,
      createTOTP,
      readTOTP,
      updateTOTP,
      sendTOTP,
      validateEmail: async () => {},
      getContext: ({form, request}) => ({...what ever I want}).
    },
    verifyTOTP,
  ),
);
```
then each of the totp function can be :

```
function sendTOTP({context}) {
  now I can do whatever I want with the context
}
```

I think we can add it as a different enhancement

**Comment by mw10013** [comment] 2024-02-13 18:07
For `v3` we are shrinking the api to ease integration. Would the following work for your use case?

```ts
authenticator.use(
  new TOTPStrategy(
    {
      secret: TOTP_ENCRYPTION_SECRET,
      // createTOTP, [removed from api]
      // readTOTP, [removed from api]
      // updateTOTP, [removed from api]
      sendTOTP: ({formData, request}) => { // form renamed to formData
        const context = getContext({formData, request});
        ...
      },
      validateEmail: async () => {},
    },
    verifyTOTP,
  ),
);
```

In either approach, the application would need to implement `getContext`. In the `v3` approach, `remix-auth-totp` would not have to know about it.

**Comment by dev-xo** [comment] 2024-02-13 19:30
What about passing context to `verify` method? As far as I know from `remix-auth`, it's intended to allow the developer to handle extra logic. 

Could it be the right candidate for it? Or am I missing something?

**Comment by mw10013** [comment] 2024-02-13 20:48
@dev-xo: Can you outline in pseudo code what context would look like with `verify`? Also, what specific use cases would it address?

Regarding your comment about `sendTOTP` - are you suggesting that a context object be passed? What would be in this context object that's not already being passed into `sendTOTP`. Again, pseudo code would help make things more concrete.

**Comment by dev-xo** [comment] 2024-02-13 22:07
Just throwing some thoughts @mw10013. At this point you understand the overall strategy better than I do, as you were in charge of `v2`, `v3`, and I'm kinda away from it, more than reviewing some of the latest updates.

As far as I know from `remix-auth`, the `verify` method was intended to handle the user and provide the developer the opportunity to handle some extra logic at that stage. I could be wrong about it, as it's something I looked into a year ago.

I'm here just to consult with you all and approve ideas based on all of your suggestions, so do not count on me to get into details, as I will probably be a bit out until we release the `v3`. After that, I will get the time to deeply look into suggestions or even touch some code.

**Comment by haus23** [comment] 2024-02-13 23:11
Hi, sorry for any unwanted noise from me. And sorry for my not perfect english.

Some little background: Last year in autumn i started developing a new remix app. I wanted to use this package/repo (and made one hint/suggestion - used a different account) - but finally dropped remix-auth-totp mainly because of the need to use the database. Meanwhile i am doing a revision of my product and im a totally fine with the v3 release. In fact i do use your dev package. And would continue to use the v3 release. That was IMHO the right decision to store data in the session.

But this issue showed off one not-so-good decision in my opinion: dropping context infos in the sendTOTP method. There are obviously use cases, where you do need access to the request or especially the formData. So if all client-related methods get the full context, they can build there "context" method or whatever alone. It would be just a helper method. Request and formData are the *context*.

Further: if we look at this brilliant summarize (helped me a lot to understand, how remix-auth-totp internally works):


 ```
   /**
   * Authenticates a user using TOTP.
   *
   * If the user is already authenticated, simply returns the user.
   *
   * | Method | Email | TOTP | Sess. Email | Sess. TOTP | Action/Logic                             |
   * |--------|-------|------|-------------|------------|------------------------------------------|
   * | POST   | ✓     | -    | -           | -          | Generate/send TOTP using form email.     |
   * | POST   | ✗     | ✗    | ✓           | -          | Generate/send TOTP for session email.    |
   * | POST   | ✗     | ✓    | ✓           | ✓          | Validate form TOTP.                      |
   * | GET    | -     | -    | ✓           | ✓          | Validate magic link TOTP.                |
```
 
Clearly the package is build around the concept of using an email for the authentication flow. I am not sure, how to genralize that. But at least it is possible to open the usage (in the v3 release) if the library gives the user full "context" infos including request and formData. There is no use-case for me, but the issue showed off some use case.

Simply take a look into the initial issue #43 @mw10013 filed and espacially at the last lines:

> @dev-xo: Please provide guidance and feedback on the initial cut. Also, can you explain why the below interfaces have the listed properties since they don't seem necessary and want to understand the background.

```

export interface SendTOTPOptions {
  ...
  form?: FormData
  request: Request
}

export interface TOTPVerifyParams {
  ...
  code?: string
  magicLink?: string
  form?: FormData
  request: Request
}

```

If relying only on the email, there is no need for this props. But obviously there are other use cases where there are usefull.

------

Just my thoughts ... I will have some time next week and will spend some minutes thinking about generalizing the way the auth flow relevant data is handled.

**Comment by mw10013** [comment] 2024-02-13 23:46
@haus23: Thank you for your thoughts and feedback. We're still finalizing `v3` and FormData and Request are going back into `SendTOTPOptions` and `TOTPVerifyParams`.

**Closed** 2024-02-14 21:34 UTC
Labels: enhancement
