### ISSUE TITLE
[ Legacy - Feat ] Add support for Cloudflare

### ISSUE THREAD

**Issue by AhmedNawaf** [dev-xo/remix-auth-totp#17] opened 2023-06-29 10:49 UTC
First of all, thank you for making such an effort into this strategy.
I played around with your demo and it's working just fine.
The problem is, when I implemented the strategy into a worker it can't identify the built-in crypto library.

**Comment by dev-xo** [comment] 2023-06-29 13:18
Hello @sa23sa! I'm not aware of it, and had no chance to try it on Cloudflare either into a worker. Can you please share your implementation / repo?

Also hace you checked the [Demo](https://github.com/dev-xo/otp-stack) implementation code? It should be working as far as I know.

Let me know, I would like to help you and fix this issue! _(in case there is one)_

**Comment by sa23sa** [comment] 2023-06-30 09:47
Hey @dev-xo 
I've checked the example code you provided and It works great on Remix app server.
Then I applied to a CF worker project, and when I submit an email it says crypto.randomInt is not defined.
Since CF Worker's runtime supports a few Node API, the Node Crypto API is not supported and It's suggested to use Web Crypto API. 
You can check the supported Node APIs here: [Node.js compatibility](https://developers.cloudflare.com/workers/platform/nodejs-compatibility/)
Sorry for not providing a repo atm.

**Comment by dev-xo** [comment] 2023-06-30 12:51
All right @sa23sa! Thanks for noticing and for having a look into it. 

I wasn't aware of it, since I had the chance to try it into CF workers, or any CF service. Not sure how hard should be to allow my Strategy to work with CF, but should not be that hard.

Also if I'm not wrong, there is some other Remix Auth Strategies that are already working fine on CF. So as far as I can take a look at their implementation, maybe I could have a fix for you, and for anyone who needs it to work on CF.

Sadly I'm kinda bussy lately, so I'm not sure when I can have a moment to look into it. Could you please reach to me directly on Remix Discord? I'm `dev-xo#9732`.

Maybe we can look into a fast fix / implementation.
Thanks for noticing! I will leave this Issue open, until I can start looking into it properly.

**Comment by markhker** [comment] 2023-07-21 21:18
@AhmedNawaf I had to write my own otp-generator for this to work on cloudflare, it uses the Web Crypto Api if its available, or the node crypto lib if in node. Here is the library: [@karimdev/remix-auth-otp](https://www.npmjs.com/package/@karimdev/remix-auth-otp)

@dev-xo The problem is not your library by itself, but the otp-generator dependency, I think you can create a [PR from my fork](https://github.com/markhker/remix-auth-otp), or just changing the 'otp-generator' to [the one I created](https://www.npmjs.com/package/@karimdev/web-otp-generator), or any other one that implements the web crypto api first if available, or in the worst case, any random generator that doesn't require node specific libraries.

**Comment by dev-xo** [comment] 2023-07-21 21:24
Yeah I know @markhker, I've been discussed this with @AhmedNawaf on discord!
I had in mind to use the Node Crypto lib for the fix, but had no time to look into it yet.

Happy to know you was able to make it work for yourself, hope this helps @AhmedNawaf also!
Gonna have a look into your implementation, in case it fits what I'm looking for, all the credits will be for you!

Thank you for the reply and for looking into this! :)

**Comment by AhmedNawaf** [comment] 2023-07-23 10:21
Great work! @markhker 

I had to make the switch to express server for bootstrapping the project ASAP.
I heard that Remix v1.19 pushed a config option for Node polyfill for built-in APIs such as node crypto. check here: [remix.config.js](https://remix.run/docs/en/main/file-conventions/remix-config#servernodebuiltinspolyfill)

Might that solve the CF issue? haven't tried it yet.

**Comment by markhker** [comment] 2023-07-23 15:55
@AhmedNawaf Yeah, I tried that first, but it doesn't work, and I don't know why 🤷‍♂️

**Comment by dev-xo** [comment] 2023-09-28 08:04
The new Remix Auth TOTP will no longer use `crypto-js` @AhmedNawaf.
Guess this will be enough to solve the Cloudflare issues?

_The repo / package has not been released yet, it will be in the next few hours.
Just renaming things and getting ready the repository._

**Closed** 2023-09-29 15:03 UTC
Labels: enhancement

**Comment by AhmedNawaf** [comment] 2023-10-03 22:19
It should be solved by now @dev-xo 
I just checked their [Node.js compatibility](https://developers.cloudflare.com/workers/runtime-apis/nodejs/), and they're supporting the `crypto` module.
From the look of the code, you're using it to generate random bytes which is supported now.

Thank you for your continuous support into this issue ❤️

**Comment by dev-xo** [comment] 2023-10-03 22:33
The `crypto` module is no longer used in this package, @AhmedNawaf. Remix Auth TOTP has been rewritten and renamed. 

If you have the opportunity, please give it a try on Cloudflare and me know how it goes!
Thank you! ❤️
